baseURL = "https://shoogle.us/new-jersey"
languageCode = "en-US"
title = "New Jersey"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "new-jersey"
